const ADD_TODO = 'ADD_TODO';
const DELETE_TODO = 'DELETE_TODO';
const TOGGLE_TODO = 'TOGGLE_TODO';
const ALL_DONE = 'ALL_DONE';
const FETCH_TODOLIST_JSON = 'FETCH_TODOLIST_JSON';
const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export default {
  ADD_TODO,
  DELETE_TODO,
  TOGGLE_TODO,
  ALL_DONE,
  FETCH_TODOLIST_JSON,
  SET_VISIBILITY_FILTER
}